 $(function(){
     //语言默认英文
     var language = $('#lang :selected').val();
             $("span:lang(en)").hide();
             $("span:lang(jp)").hide();
             $("span:lang(ch)").show();
             $("a:lang(en)").hide();
             $("a:lang(jp)").hide();
             $("a:lang(ch)").show();
             $("h1:lang(en)").hide();
             $("h1:lang(jp)").hide();
             $("h1:lang(ch)").show();
             $("h2:lang(en)").hide();
             $("h2:lang(jp)").hide();
             $("h2:lang(ch)").show();
             $("h3:lang(en)").hide();
             $("h3:lang(jp)").hide();
             $("h3:lang(ch)").show();
             $("h4:lang(en)").hide();
             $("h4:lang(jp)").hide();
             $("h4:lang(ch)").show();
             $("p:lang(en)").hide();
             $("p:lang(jp)").hide();
             $("p:lang(ch)").show();
     //用语言种类选择
     $('#lang').change(function(){
         language = $('#lang :selected').val();
         if(language == "en"){
             $("span:lang(ch)").hide();
             $("span:lang(jp)").hide();
             $("span:lang(en)").show();
             $("a:lang(ch)").hide();
             $("a:lang(jp)").hide();
             $("a:lang(en)").show();
             $("h1:lang(ch)").hide();
             $("h1:lang(jp)").hide();
             $("h1:lang(en)").show();
             $("h2:lang(ch)").hide();
             $("h2:lang(jp)").hide();
             $("h2:lang(en)").show();
             $("h3:lang(ch)").hide();
             $("h3:lang(jp)").hide();
             $("h3:lang(en)").show();
             $("h4:lang(ch)").hide();
             $("h4:lang(jp)").hide();
             $("h4:lang(en)").show();
             $("p:lang(ch)").hide();
             $("p:lang(jp)").hide();
             $("p:lang(en)").show();
         }
         if(language == "ch"){
             $("span:lang(en)").hide();
             $("span:lang(jp)").hide();
             $("span:lang(ch)").show();
             $("a:lang(en)").hide();
             $("a:lang(jp)").hide();
             $("a:lang(ch)").show();
             $("h1:lang(en)").hide();
             $("h1:lang(jp)").hide();
             $("h1:lang(ch)").show();
             $("h2:lang(en)").hide();
             $("h2:lang(jp)").hide();
             $("h2:lang(ch)").show();
             $("h3:lang(en)").hide();
             $("h3:lang(jp)").hide();
             $("h3:lang(ch)").show();
             $("h4:lang(en)").hide();
             $("h4:lang(jp)").hide();
             $("h4:lang(ch)").show();
             $("p:lang(en)").hide();
             $("p:lang(jp)").hide();
             $("p:lang(ch)").show();
         }
         if(language == "jp"){
             $("span:lang(ch)").hide();
             $("span:lang(en)").hide();
             $("span:lang(jp)").show();
             $("a:lang(ch)").hide();
             $("a:lang(en)").hide();
             $("a:lang(jp)").show();
             $("h1:lang(ch)").hide();
             $("h1:lang(en)").hide();
             $("h1:lang(jp)").show();
             $("h2:lang(ch)").hide();
             $("h2:lang(en)").hide();
             $("h2:lang(jp)").show();
             $("h3:lang(ch)").hide();
             $("h3:lang(en)").hide();
             $("h3:lang(jp)").show();
             $("h4:lang(ch)").hide();
             $("h4:lang(en)").hide();
             $("h4:lang(jp)").show();
             $("p:lang(ch)").hide();
             $("p:lang(en)").hide();
             $("p:lang(jp)").show();
         }
     })
 })